### ISSUE TITLE
stud.csv program

### ISSUE THREAD

**Issue by 23bca287** [vtcbca/internal-exam-23bca287#2]
![internal](https://github.com/user-attachments/assets/aa634cae-62ba-44b3-af89-399a1ccb6ef8)

in this program coding are almost true.

but coding was end then program data are not display. so please solve this program.

**Comment by 23bca286** [comment]
This program is wrong

**Comment by 23bca274** [comment]
Use following syntax

import csv
with open("location_of csv file","r")as f:
    r=csv.reader(f)
    for row in r:
        print(row)

**Comment by 23bca287** [comment]
this issue is solve.
