### ISSUE TITLE
second error

### ISSUE THREAD

**Issue by 23bca287** [vtcbca/internal-exam-23bca287#3]
![2 error](https://github.com/user-attachments/assets/283c17e9-6b0d-41c2-add3-a541e8281d68)

This was almost same error, so please replay.

**Comment by 23bca274** [comment]
> ![2 error](https://github.com/user-attachments/assets/283c17e9-6b0d-41c2-add3-a541e8281d68)
> 
> This was almost same error, so please replay.


Don't use " = " assignment after " with open " 

Write this instead 👇🏻 

with open("location_of csv file","r")as f:

**Comment by 23bca287** [comment]
this issue is solve.
